# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './assets/storage.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_storageScreen(object):
    def setupUi(self, storageScreen):
        storageScreen.setObjectName("storageScreen")
        storageScreen.resize(649, 505)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(storageScreen.sizePolicy().hasHeightForWidth())
        storageScreen.setSizePolicy(sizePolicy)
        storageScreen.setMinimumSize(QtCore.QSize(649, 505))
        storageScreen.setMaximumSize(QtCore.QSize(649, 505))
        self.layoutWidget = QtWidgets.QWidget(storageScreen)
        self.layoutWidget.setGeometry(QtCore.QRect(3, 10, 641, 491))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMaximumSize)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setObjectName("verticalLayout")
        self.storageView = QtWidgets.QTableView(self.layoutWidget)
        self.storageView.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.storageView.setFrameShadow(QtWidgets.QFrame.Raised)
        self.storageView.setLineWidth(0)
        self.storageView.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.storageView.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.storageView.setGridStyle(QtCore.Qt.DashDotDotLine)
        self.storageView.setCornerButtonEnabled(False)
        self.storageView.setObjectName("storageView")
        self.verticalLayout.addWidget(self.storageView)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.recallButton = QtWidgets.QPushButton(self.layoutWidget)
        self.recallButton.setObjectName("recallButton")
        self.horizontalLayout.addWidget(self.recallButton)
        self.removeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.removeButton.setObjectName("removeButton")
        self.horizontalLayout.addWidget(self.removeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout)

        self.retranslateUi(storageScreen)
        QtCore.QMetaObject.connectSlotsByName(storageScreen)

    def retranslateUi(self, storageScreen):
        _translate = QtCore.QCoreApplication.translate
        storageScreen.setWindowTitle(_translate("storageScreen", "Storage"))
        self.recallButton.setText(_translate("storageScreen", "Recall"))
        self.removeButton.setText(_translate("storageScreen", "Remove"))
